### PR TITLE
Upgraded erlang.mk for otp 23

### PR DESCRIPTION
**Pull request by tsenturk**
> 2020/03/25: The `-lerl_interface` argument has been removed
            from the default `LDLIBS`. This is an old library
            that is getting removed in OTP-23 and should no
            longer be used. Note that the default still includes
            `-lei` which is part of the Erlang/OTP Erl_Interface
            *application* but is built as a separate C library.
            The removal only applies to `-lerl_interface` itself.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@essen @dumbbell is our our fork needed for this library or can we go with this PR?

**Comment by essen** [comment]
I think the fork has nothing RabbitMQ-specific it's just a slightly older version. I think the Erlang.mk file being replaced was from mainline anyway. Assuming the project still compiles and works, the PR is fine.

**Comment by michaelklishin** [comment]
That it does.

**Comment by tsenturk** [comment]
thank you @michaelklishin and @essen

**Pull request merged**
